version: '0.1'
services:

    flask:                                             
        build: './flask_docker'   
        platform : linux/amd64                     
        container_name: flask_container
        volumes:                                        
            - ./models/current_model/:/flask/model/
            - ./dags/src/:/flask/src/
        ports:
            - "5002:5000"                               
        # command: 'python -m flask run --host 0.0.0.0 --port 5000'
        stdin_open : True

